### ISSUE TITLE
(Feature) Automatically embed links and images in main discussion

### ISSUE THREAD

**Issue by cnvo** [dessalines/flowchat#74]
Inputting a URL in the "Link" field in a discussion should get the contents of the requested page.
Image (if any)
Title - If there's a title (which there should be), it should autofill the "Title" input.
Description - If there's a description then it should autofill the textarea.

Actually, now that I think about it what do you think about adding an image upload field for the main discussion?

Just throwing some ideas out here. I'm visualizing something awesome in the making.

**Comment by dessalines** [comment]
I don't think I want it to actually fetch the contents of another http page, but I agree for non-image type links, [example](https://flow-chat.com/#/discussion/315), it'd probably good to have the full link more prominent, rather than the little link button it is now. 

There is a title field already for discussions.

> Description - If there's a description then it should autofill the textarea.

Not sure what this means... you create your own discussion descriptions.

**Comment by cnvo** [comment]
Sorry it was morning when I actually wrote that I didn't really have my coffee. 

What I mean by fetching contents is really just extracting information about the actual web pages (sort of like what Reddit does) to automatically fill in the given fields provided in the form.
